@startuml "diagramaDeEstado"

title "Reto06 \n Ejercicio i"

skinparam title{
  BorderColor blue
  BorderThickness 2
  BorderRoundCorner 10
  BackgroundColor 000000-blue
  FontColor FFFFFF
}

skinparam State{
  BackgroundColor 093949-black
  FontColor FFFFFF
  BorderThickness 2
  BorderColor cyan
}
  
[*]-->encargarPedido : establecer contacto con el cliente
encargarPedido: entry/ preguntar por disponibilidad
encargarPedido: do/ encargar producto
encargarPedido: do/ obtener datos del cliente
encargarPedido: exit/ guardar datos del pedido

encargarPedido->validarPedido: procesarPedido()
validarPedido: entry/ solicitar datos del pedido
validarPedido: do/ examinar los datos del pedido
validarPedido: do/ verificar disponibilidad del producto
validarPedido: exit/ confirmar datos del pedido

validarPedido-->pagoPedido: cobrarPedido() 
pagoPedido: entry/ seleccionar metodo de pago
pagoPedido: do/ pagar pedido
pagoPedido: exit/ confirmar pago

state envio <<choice>>
pagoPedido->envio: empaquetarPedido()
envio --> enviarPedidoNormal : [pedido urgente = no]
envio --> enviopedidoUrgente : [pedido urgente = si]

enviarPedidoNormal: entry/ contactar a los transportistas
enviarPedidoNormal: do/ dar detalles de la direccion de envio
enviarPedidoNormal: do/ confirmar fecha salida de los transportistas 
enviarPedidoNormal: exit/entregar pedido a los transportistas 

enviarPedidoNormal--->finiquitarEnvio: dar cervezas a los transportistas
finiquitarEnvio: entry/enviar recibo al cliente
finiquitarEnvio: exit/ añadir cliente a la lista de satisfechos

enviopedidoUrgente: entry/ contactar a los transportistas
enviopedidoUrgente: do/ dar detalles de la direccion de envio
enviopedidoUrgente: do/ verificar disponibilidad para entrega inmediata
enviopedidoUrgente: exit/ entregar pedido a los transportistas 

finiquitarEnvio-->[*] : confirmar salida del envio  
enviopedidoUrgente---->[*] : confirmar salida del envio
 
@enduml